# ==============================================================================
# Ansible Inventory Template for Azure Elasticsearch VM
# ==============================================================================
# 1. Copy file này thành `inventory.ini` (file inventory.ini đã được .gitignore bảo vệ an toàn):
#    cp inventory.example.ini inventory.ini
# 2. Điền IP và Password của máy ảo Azure VM vào bên dưới:
# ==============================================================================

[elasticsearch_servers]
azure_es_node ansible_host=YOUR_AZURE_VM_PUBLIC_IP ansible_user=azureuser ansible_ssh_pass="YOUR_VM_PASSWORD" elasticsearch_password="YOUR_ES_PASSWORD"

[elasticsearch_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
